# content taken from https://blog.ouseful.info/2021/11/10/simple-jupytext-github-action-to-update-jupyter-ipynb-notebooks-from-markdown/
name: convert-jupyter-notebooks

on:
  push

jobs:

  create-jupyter-notebooks:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]

    # required by https://github.com/stefanzweifel/git-auto-commit-action
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:

      # Checkout
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      # Test for changed notebooks, see https://github.com/dorny/paths-filter?tab=readme-ov-file#examples
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          # Enable listing of files matching each filter.
          # Paths to files will be available in a `${FILTER_NAME}_files` output variable.
          # Paths will be escaped and space-delimited.
          # Output is usable as command-line argument list in Linux shell
          list-files: shell

          # In this example changed markdown will be spellchecked using aspell
          # If we specify we are only interested in added or modified files, deleted files are ignored
          filters: |
            notebooks:
              - added|modified: 'notebooks/*.py'
            dependencies:
              - 'requirements.txt'
          # Should we also identify deleted md files
          # and then try to identify (and delete) .ipynb docs otherwise paired to them?
          # For example, remove .ipynb file on same path ($FILEPATH is a file with .md suffix)
          # rm ${FILEPATH%.md}.ipynb

      - name: Install Packages if changed files
        #if: ${{ steps.filter.outputs.dependencies == 'true' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install --extra-index-url https://download.pytorch.org/whl/cpu torch torchvision
          python -m pip install -r ./requirements.txt

      - name: Synch changed files
        if: ${{ steps.filter.outputs.notebooks == 'true' }}
        run: |
          # If a command accepts a list of files,
          # we can pass them directly
          # This will only synch files if the md doc include jupytext metadata
          # and has one or more paired docs defined
          # The timestamp on the synched ipynb file will be set to the
          # same time as the changed markdown file
          jupytext --use-source-timestamp --to ipynb ${{ steps.filter.outputs.notebooks_files }}
 
        # Auto commit any updated notebook files
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # This would be more useful if the git hash were referenced?
          commit_message: automated jupytext conversion of py:percent files to ipynb
          file_pattern: 'notebooks/*ipynb'
          status_options: '-u'
